server:
	gcc server.c ../.src/jsocket6.4.c -o ../server
client:
	gcc client.c ../.src/jsocket6.4.c -o ../client
all:
	gcc server.c ../.src/jsocket6.4.c -o ../server
	gcc client.c ../.src/jsocket6.4.c -o ../client
clean:
	rm ../server ../client ../*~ ../*.o
